/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BreadCrumb: typeof import('./components/BreadCrumb.vue')['default']
    CartSidePanel: typeof import('./components/CartSidePanel.vue')['default']
    MenuSidePanel: typeof import('./components/MenuSidePanel.vue')['default']
    QuantityInput: typeof import('./components/QuantityInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
  }
}
